version: '3.8'
services:
  node-app: 
    build:
      context: .
      dockerfile: Dockerfile
    image: git-backup:1.0.0
    env_file:
      - stack.env
    ports:
      - '33776:33776'
    restart: always
    network_mode: bridge
    volumes:
      - cert-volume:/app/certificate
volumes:
  cert-volume:
    external: true